# Generated by Django 3.2.2 on 2024-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_auto_20240323_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('SRKIT', 'SRKIT'), ('VIJAYA', 'VIJAYA')], max_length=29),
        ),
    ]
